/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Card, Weather } from './types';

export const CARD_DEFINITIONS: Record<string, Card> = {
  farm: {
    id: 'farm',
    name: '农场',
    icon: '🌾',
    type: 'build',
    costGold: 2,
    costStone: 0,
    costWood: 0,
    effect: '每回合产出 2 块金币（不提供繁荣度）',
    income: { gold: 2 },
    prosperity: 0,
  },
  mine: {
    id: 'mine',
    name: '矿场',
    icon: '⛏️',
    type: 'build',
    costGold: 3,
    costStone: 0,
    costWood: 0,
    effect: '每回合产出 2 堆石料（不提供繁荣度）',
    income: { stone: 2 },
    prosperity: 0,
  },
  lumber: {
    id: 'lumber',
    name: '伐木场',
    icon: '🪓',
    type: 'build',
    costGold: 3,
    costStone: 0,
    costWood: 0,
    effect: '每回合产出 2 捆木材（不提供繁荣度）',
    income: { wood: 2 },
    prosperity: 0,
  },
  market: {
    id: 'market',
    name: '市场',
    icon: '🏪',
    type: 'build',
    costGold: 5,
    costStone: 0,
    costWood: 0,
    effect: '每回合产出 3 块金币，繁荣度 +2',
    income: { gold: 3 },
    prosperity: 2,
  },
  house: {
    id: 'house',
    name: '民居',
    icon: '🏠',
    type: 'build',
    costGold: 2,
    costStone: 0,
    costWood: 1,
    effect: '每回合产出 1 块金币，繁荣度 +1',
    income: { gold: 1 },
    prosperity: 1,
  },
  barracks: {
    id: 'barracks',
    name: '兵营',
    icon: '🛡️',
    type: 'military',
    costGold: 3,
    costStone: 2,
    costWood: 0,
    effect: '第一座繁荣+1并解锁主动攻击；多建不加繁荣，但每次主动攻击及突袭/掠夺掠夺量永久+1',
    prosperity: 1,
    unlocksAttack: true,
  },
  blacksmith: {
    id: 'blacksmith',
    name: '铁匠铺',
    icon: '🔨',
    type: 'build',
    costGold: 4,
    costStone: 4,
    costWood: 4,
    effect: '解锁 铁质城墙 与 攻城车，繁荣度+2',
    prosperity: 2,
  },
  academy: {
    id: 'academy',
    name: '学院',
    icon: '📚',
    type: 'dev',
    costGold: 5,
    costStone: 2,
    costWood: 10,
    effect: '繁荣度+3。若有防御点数，每2回合结束额外产出1繁荣度',
    prosperity: 3,
  },
  temple: {
    id: 'temple',
    name: '神殿',
    icon: '⛪',
    type: 'dev',
    costGold: 3,
    costStone: 2,
    costWood: 0,
    effect: '繁荣度+2，并立即提供 1 个建筑防御点（每2回合完全恢复）',
    prosperity: 2,
    defense: 1,
  },
  treasury: {
    id: 'treasury',
    name: '金库',
    icon: '💰',
    type: 'build',
    costGold: 4,
    costStone: 1,
    costWood: 0,
    effect: '每回合产出 4 块金币，繁荣度 +2',
    income: { gold: 4 },
    prosperity: 2,
  },
  witchAltar: {
    id: 'witchAltar',
    name: '巫术祭台',
    icon: '🪄',
    type: 'dev',
    costGold: 15,
    costStone: 10,
    costWood: 5,
    effect: '【珍稀珍贵】需要神殿与学院。每2回合可使用防御值选择指定天气2回合',
    prosperity: 5,
  },
  raid: {
    id: 'raid',
    name: '突袭卡',
    icon: '🗡️',
    type: 'military',
    costGold: 3,
    costStone: 1,
    costWood: 0,
    effect: '消耗卡牌抢夺目标随机3点资源。多建兵营可暴兵增加单次掠夺量',
    attackPower: 3,
    requiresBarracks: true,
  },
  plunder: {
    id: 'plunder',
    name: '掠夺卡',
    icon: '☠️',
    type: 'military',
    costGold: 5,
    costStone: 2,
    costWood: 0,
    effect: '消耗卡牌抢夺目标随机5点资源。多建兵营可暴兵增加单次掠夺量',
    attackPower: 5,
    requiresBarracks: true,
  },
  catapult: {
    id: 'catapult',
    name: '投石车',
    icon: '🪨',
    type: 'military',
    costGold: 6,
    costStone: 4,
    costWood: 2,
    effect: '消耗卡牌。使目标随机1个正常建筑失效(无法运作)2回合',
    catapult: true,
    requiresBarracks: true,
  },
  siege: {
    id: 'siege',
    name: '攻城车',
    icon: '🐏',
    type: 'military',
    costGold: 8,
    costStone: 6,
    costWood: 3,
    effect: '消耗卡牌（需要铁匠铺）。使目标2回合防御点数归零（完全无法防守）',
    siege: true,
    requiresBarracks: true,
    requiresBlacksmith: true,
  },
  woodFence: {
    id: 'woodFence',
    name: '木制离笆',
    icon: '🪵',
    type: 'defense',
    costGold: 1,
    costStone: 0,
    costWood: 1,
    effect: '提供 1 点消耗性防御力(被攻击后消失)',
    defensePoints: 1,
  },
  stoneWall: {
    id: 'stoneWall',
    name: '石制围墙',
    icon: '🧱',
    type: 'defense',
    costGold: 2,
    costStone: 2,
    costWood: 0,
    effect: '提供 3 点消耗性防御力(被攻击后消失)',
    defensePoints: 3,
  },
  ironWall: {
    id: 'ironWall',
    name: '铁质城墙',
    icon: '🏰',
    type: 'defense',
    costGold: 5,
    costStone: 4,
    costWood: 2,
    effect: '提供 10 点消耗性防御力，需要铁匠铺作为前置',
    defensePoints: 10,
    requiresBlacksmith: true,
  },
  feast: {
    id: 'feast',
    name: '盛宴',
    icon: '🍗',
    type: 'resource',
    costGold: 3,
    costStone: 0,
    costWood: 0,
    effect: '美味佳肴：购买时立即获得 6 金币',
    bonus: { gold: 6 },
  },
  caravan: {
    id: 'caravan',
    name: '商队',
    icon: '🐫',
    type: 'resource',
    costGold: 2,
    costStone: 0,
    costWood: 0,
    effect: '远途交易：购买时立即获得 4金币 以及 石料+2, 木材+2',
    bonus: { gold: 4, stone: 2, wood: 2 },
  },
  quarry: {
    id: 'quarry',
    name: '采石工',
    icon: '⛰️',
    type: 'resource',
    costGold: 2,
    costStone: 0,
    costWood: 0,
    effect: '采石热潮：立即获得 4 石料',
    bonus: { stone: 4 },
  },
  woodcut: {
    id: 'woodcut',
    name: '伐木工',
    icon: '🪓',
    type: 'resource',
    costGold: 2,
    costStone: 0,
    costWood: 0,
    effect: '伐木作业：立即获得 4 木材',
    bonus: { wood: 4 },
  },
  travelingMerchant: {
    id: 'travelingMerchant',
    name: '旅行商人',
    icon: '🧳',
    type: 'resource',
    costGold: 0,
    costStone: 0,
    costWood: 1,
    effect: '消耗 1 木材：立即增加此回合 3 次免费商店刷新费用',
    freeRefreshes: 3,
  },
  weatherShard: {
    id: 'weatherShard',
    name: '天气巫术碎片',
    icon: '🔮',
    type: 'resource',
    costGold: 2,
    costStone: 0,
    costWood: 0,
    effect: '筹齐 2 张相同的巫术碎片：随机强制触发天灾或瑞雨3回合',
    isFragment: true,
    fragmentType: 'weather',
    fragmentNeed: 2,
  },
  prosperityShard: {
    id: 'prosperityShard',
    name: '繁荣巫术碎片',
    icon: '✨',
    type: 'resource',
    costGold: 3,
    costStone: 0,
    costWood: 1,
    effect: '筹齐 2 张相同的繁荣碎片：立即爆发并触发当前所有运作建筑的效果产出',
    isFragment: true,
    fragmentType: 'prosperity',
    fragmentNeed: 2,
  },
  ancientMap: {
    id: 'ancientMap',
    name: '远古宝藏',
    icon: '💎',
    type: 'resource',
    costGold: 2, // will be randomized dynamically in shop, default fallback is 2
    costStone: 0,
    costWood: 0,
    effect: '远古宝藏：50%概率挖得 2-9 金币；50%概率掘得 1-7 石料与 1-5 木材',
    isRandomResource: true,
  },
  fogSpell: {
    id: 'fogSpell',
    name: '迷雾法术',
    icon: '🌫️',
    type: 'military',
    costGold: 2,
    costStone: 0,
    costWood: 0,
    effect: '战争法术：指定一座城池，隐藏其资源。轮次结束时若其藏有未花完的金币，你将尽数夺走抢走！',
    requiresBarracks: true,
  },
  wishingWell: {
    id: 'wishingWell',
    name: '许愿井',
    icon: '⛲',
    type: 'dev',
    costGold: 15,
    costStone: 15,
    costWood: 15,
    effect: '【珍稀珍贵】提供5点繁荣度。本城市免疫一切负面天候灾难，且每次商店刷新至少展示 1 枚资源物资产出卡！',
    prosperity: 5,
  },
  tradeMarket: {
    id: 'tradeMarket',
    name: '贸易集市',
    icon: '🎪',
    type: 'dev',
    costGold: 6,
    costStone: 6,
    costWood: 6,
    effect: '解锁🐫特殊背包【贸易线路】。可在本回合及后续回合激活，向其他领主发售木材或石料，对方在其回合的商店中买入后将为您增加 1点 繁荣度并结算支付金币！',
    prosperity: 0,
  },
  tradeCargo: {
    id: 'tradeCargo',
    name: '边境贸易物资',
    icon: '🐫',
    type: 'resource',
    costGold: 0,
    costStone: 0,
    costWood: 0,
    effect: '购买可获得对方城池出售的同等贸易物资，价格对应金币。认购后将给出售方城市增加 1点 繁荣度！',
  },
  warShard: {
    id: 'warShard',
    name: '战争巫术碎片',
    icon: '💥',
    type: 'resource',
    costGold: 4,
    costStone: 0,
    costWood: 0,
    effect: '筹齐 2 张战争碎片：首都立马对其他所有敌城发动一轮 5 点火力的掠夺军出击！',
    isFragment: true,
    fragmentType: 'war',
    fragmentNeed: 2,
  },
  guardianShard: {
    id: 'guardianShard',
    name: '守护巫术碎片',
    icon: '🔰',
    type: 'resource',
    costGold: 4,
    costStone: 0,
    costWood: 0,
    effect: '筹齐 2 张守护碎片：城内防务壁垒守护神光附体，防御值瞬间翻倍并持续 2 轮！',
    isFragment: true,
    fragmentType: 'guardian',
    fragmentNeed: 2,
  },
};

export const WEATHERS: Weather[] = [
  {
    name: '大晴天',
    icon: '☀️',
    desc: '万里无云，民生安康。所有运作中、提供产出的生产类建筑，其产出的资源数值均额外 +1！',
    color: 'from-amber-600/30 to-yellow-500/20',
  },
  {
    name: '雨天',
    icon: '🌧️',
    desc: '细雨微风，城防泥泞。所有玩家由于木石受潮，防御效果削弱减半！',
    defenseHalve: true,
    color: 'from-blue-900/40 to-slate-900/40',
  },
  {
    name: '台风',
    icon: '🌪️',
    desc: '台风过境，战乱不售。港口封闭，由于暴风肆虐，市场本回合不再刷新、售卖任何军事及防御卡！',
    hideMilitary: true,
    color: 'from-purple-950/40 to-slate-900/40',
  },
  {
    name: '阴天',
    icon: '☁️',
    desc: '微风昏暗，黄沙满天。狂烈沙尘暴将全图所有城邦（包含玩家自身城市）的所有资源储备数值通通遮蔽隐藏！',
    hideResources: true,
    color: 'from-slate-700/30 to-zinc-850/20',
  },
  {
    name: '暴风雪',
    icon: '❄️',
    desc: '寒风凛冽，物产停工。极端极寒天气，所有人城邦建筑经济资源产出直接被迫减半（向上取整）！',
    incomeHalve: true,
    color: 'from-cyan-900/30 to-blue-950/25',
  },
  {
    name: '旱灾',
    icon: '🔥',
    desc: '烈日灼天，赤地千里。所有建筑物（包括生产类建筑）产量缩减一半，单数情况下向下取整（如产出1/3变为0/1）！',
    color: 'from-orange-850/40 to-yellow-950/30',
  },
];
